//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shadows {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shadows.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm deletion ähnelt.
        /// </summary>
        internal static string ConfirmDirectoryDeletionCaption {
            get {
                return ResourceManager.GetString("ConfirmDirectoryDeletionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to move the selected folder to the recycle bin? ähnelt.
        /// </summary>
        internal static string ConfirmDirectoryDeletionText {
            get {
                return ResourceManager.GetString("ConfirmDirectoryDeletionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm Exit ähnelt.
        /// </summary>
        internal static string ConfirmExitCaption {
            get {
                return ResourceManager.GetString("ConfirmExitCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to close Shadows? ähnelt.
        /// </summary>
        internal static string ConfirmExitText {
            get {
                return ResourceManager.GetString("ConfirmExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm deletion ähnelt.
        /// </summary>
        internal static string ConfirmFileDeletionCaption {
            get {
                return ResourceManager.GetString("ConfirmFileDeletionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to move the selected files to the recycle bin? ähnelt.
        /// </summary>
        internal static string ConfirmFileDeletionText {
            get {
                return ResourceManager.GetString("ConfirmFileDeletionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deleted {0} ähnelt.
        /// </summary>
        internal static string EmptyFoldersDeletedFolder {
            get {
                return ResourceManager.GetString("EmptyFoldersDeletedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error deleting &quot;{0}&quot; - {1} ähnelt.
        /// </summary>
        internal static string EmptyFoldersDeletionError {
            get {
                return ResourceManager.GetString("EmptyFoldersDeletionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No folder selected ähnelt.
        /// </summary>
        internal static string EmptyFoldersErrorNoFolderSelectedCaption {
            get {
                return ResourceManager.GetString("EmptyFoldersErrorNoFolderSelectedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You must specify a folder to search. ähnelt.
        /// </summary>
        internal static string EmptyFoldersErrorNoFolderSelectedText {
            get {
                return ResourceManager.GetString("EmptyFoldersErrorNoFolderSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scanning {0} ähnelt.
        /// </summary>
        internal static string EmptyFoldersScanningFolder {
            get {
                return ResourceManager.GetString("EmptyFoldersScanningFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skipping &quot;{0}&quot; - {1} ähnelt.
        /// </summary>
        internal static string EmptyFoldersSearchError {
            get {
                return ResourceManager.GetString("EmptyFoldersSearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Searching ... ähnelt.
        /// </summary>
        internal static string EmptyFoldersSearching {
            get {
                return ResourceManager.GetString("EmptyFoldersSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search in progress ähnelt.
        /// </summary>
        internal static string EmptyFoldersSearchInProgressCaption {
            get {
                return ResourceManager.GetString("EmptyFoldersSearchInProgressCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are currently searching and deleting empty folders. Are you sure you wish to abort the search? ähnelt.
        /// </summary>
        internal static string EmptyFoldersSearchInProgressText {
            get {
                return ResourceManager.GetString("EmptyFoldersSearchInProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} folders deleted ähnelt.
        /// </summary>
        internal static string EmptyFoldersXFoldersDeleted {
            get {
                return ResourceManager.GetString("EmptyFoldersXFoldersDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} folders scanned ähnelt.
        /// </summary>
        internal static string EmptyFoldersXFoldersScanned {
            get {
                return ResourceManager.GetString("EmptyFoldersXFoldersScanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Already added ähnelt.
        /// </summary>
        internal static string ErrorFolderAlreadyAddedCaption {
            get {
                return ResourceManager.GetString("ErrorFolderAlreadyAddedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The directory &quot;{0}&quot; has already been added. ähnelt.
        /// </summary>
        internal static string ErrorFolderAlreadyAddedText {
            get {
                return ResourceManager.GetString("ErrorFolderAlreadyAddedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid custom file types ähnelt.
        /// </summary>
        internal static string ErrorIncorrectCustomFileTypesCaption {
            get {
                return ResourceManager.GetString("ErrorIncorrectCustomFileTypesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The custom file types were not specified properly. Please correct them and try again. ähnelt.
        /// </summary>
        internal static string ErrorIncorrectCustomFileTypesText {
            get {
                return ResourceManager.GetString("ErrorIncorrectCustomFileTypesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid regular expression ähnelt.
        /// </summary>
        internal static string ErrorInvalidRegexEnteredCaption {
            get {
                return ResourceManager.GetString("ErrorInvalidRegexEnteredCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified regular expression is invalid. ähnelt.
        /// </summary>
        internal static string ErrorInvalidRegexEnteredText {
            get {
                return ResourceManager.GetString("ErrorInvalidRegexEnteredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File not found ähnelt.
        /// </summary>
        internal static string ErrorLogfileNotFoundCaption {
            get {
                return ResourceManager.GetString("ErrorLogfileNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to find the log file. Maybe nothing was logged yet or the file has been deleted. ähnelt.
        /// </summary>
        internal static string ErrorLogfileNotFoundText {
            get {
                return ResourceManager.GetString("ErrorLogfileNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No comparison criterion ähnelt.
        /// </summary>
        internal static string ErrorNoComparisonCriterionCheckedCaption {
            get {
                return ResourceManager.GetString("ErrorNoComparisonCriterionCheckedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have to specify at least one comparison criterion. ähnelt.
        /// </summary>
        internal static string ErrorNoComparisonCriterionCheckedText {
            get {
                return ResourceManager.GetString("ErrorNoComparisonCriterionCheckedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No file types ähnelt.
        /// </summary>
        internal static string ErrorNoFileTypesSpecifiedCaption {
            get {
                return ResourceManager.GetString("ErrorNoFileTypesSpecifiedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You must specify at least one file type. ähnelt.
        /// </summary>
        internal static string ErrorNoFileTypesSpecifiedText {
            get {
                return ResourceManager.GetString("ErrorNoFileTypesSpecifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No directories added ähnelt.
        /// </summary>
        internal static string ErrorNoFoldersAddedCaption {
            get {
                return ResourceManager.GetString("ErrorNoFoldersAddedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have to specify at least one directory to search. ähnelt.
        /// </summary>
        internal static string ErrorNoFoldersAddedText {
            get {
                return ResourceManager.GetString("ErrorNoFoldersAddedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Already added ähnelt.
        /// </summary>
        internal static string ErrorParentFolderAlreadyAddedCaption {
            get {
                return ResourceManager.GetString("ErrorParentFolderAlreadyAddedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This directory is a subdirectory of &quot;{0}&quot; and therefore already included in the search. ähnelt.
        /// </summary>
        internal static string ErrorParentFolderAlreadyAddedText {
            get {
                return ResourceManager.GetString("ErrorParentFolderAlreadyAddedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deleted directory ähnelt.
        /// </summary>
        internal static string ErrorRecycledFolderAddedCaption {
            get {
                return ResourceManager.GetString("ErrorRecycledFolderAddedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This directory has been deleted and cannot be searched. ähnelt.
        /// </summary>
        internal static string ErrorRecycledFolderAddedText {
            get {
                return ResourceManager.GetString("ErrorRecycledFolderAddedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No administrator rights ähnelt.
        /// </summary>
        internal static string ErrorSystemFilesWithoutAdminPrivilegesCaption {
            get {
                return ResourceManager.GetString("ErrorSystemFilesWithoutAdminPrivilegesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Administrator rights are required to search system files. Please exit the program and restart it with administrator permissions. ähnelt.
        /// </summary>
        internal static string ErrorSystemFilesWithoutAdminPrivilegesText {
            get {
                return ResourceManager.GetString("ErrorSystemFilesWithoutAdminPrivilegesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to open directory ähnelt.
        /// </summary>
        internal static string ErrorUnableToAccessFolderCaption {
            get {
                return ResourceManager.GetString("ErrorUnableToAccessFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot open directory &quot;{0}&quot;. Maybe you don&apos;t have permissions to access it or it was renamed or deleted. ähnelt.
        /// </summary>
        internal static string ErrorUnableToAccessFolderText {
            get {
                return ResourceManager.GetString("ErrorUnableToAccessFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to delete file ähnelt.
        /// </summary>
        internal static string ErrorUnableToDeleteFileCaption {
            get {
                return ResourceManager.GetString("ErrorUnableToDeleteFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot delete file &quot;{0}&quot; - {1} ähnelt.
        /// </summary>
        internal static string ErrorUnableToDeleteFileText {
            get {
                return ResourceManager.GetString("ErrorUnableToDeleteFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while opening folder ähnelt.
        /// </summary>
        internal static string ErrorUnableToOpenFolderAndSelectItemsCaption {
            get {
                return ResourceManager.GetString("ErrorUnableToOpenFolderAndSelectItemsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot open the requested folder.
        ///
        ///Error Code: {0}
        ///Error Message: {1} ähnelt.
        /// </summary>
        internal static string ErrorUnableToOpenFolderAndSelectItemsText {
            get {
                return ResourceManager.GetString("ErrorUnableToOpenFolderAndSelectItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to open folder ähnelt.
        /// </summary>
        internal static string ErrorUnableToOpenFolderCaption {
            get {
                return ResourceManager.GetString("ErrorUnableToOpenFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot open folder &quot;{0}&quot; - {1} ähnelt.
        /// </summary>
        internal static string ErrorUnableToOpenFolderText {
            get {
                return ResourceManager.GetString("ErrorUnableToOpenFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to rename file ähnelt.
        /// </summary>
        internal static string ErrorUnableToRenameFileCaption {
            get {
                return ResourceManager.GetString("ErrorUnableToRenameFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot rename file &quot;{0}&quot; - {1} ähnelt.
        /// </summary>
        internal static string ErrorUnableToRenameFileText {
            get {
                return ResourceManager.GetString("ErrorUnableToRenameFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to open file ähnelt.
        /// </summary>
        internal static string ErrorUnableToStartProcessCaption {
            get {
                return ResourceManager.GetString("ErrorUnableToStartProcessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot open file &quot;{0}&quot; - {1} ähnelt.
        /// </summary>
        internal static string ErrorUnableToStartProcessText {
            get {
                return ResourceManager.GetString("ErrorUnableToStartProcessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Virtual directory ähnelt.
        /// </summary>
        internal static string ErrorVirtualFolderAddedCaption {
            get {
                return ResourceManager.GetString("ErrorVirtualFolderAddedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Virtual directories cannot be added to the search. ähnelt.
        /// </summary>
        internal static string ErrorVirtualFolderAddedText {
            get {
                return ResourceManager.GetString("ErrorVirtualFolderAddedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Shadows were found. ähnelt.
        /// </summary>
        internal static string SearchCompletedBalloonText {
            get {
                return ResourceManager.GetString("SearchCompletedBalloonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search completed ähnelt.
        /// </summary>
        internal static string SearchCompletedBalloonTitle {
            get {
                return ResourceManager.GetString("SearchCompletedBalloonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counting files ... ähnelt.
        /// </summary>
        internal static string SearchCountingFiles {
            get {
                return ResourceManager.GetString("SearchCountingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File {0} of {1} ähnelt.
        /// </summary>
        internal static string SearchFileXOfY {
            get {
                return ResourceManager.GetString("SearchFileXOfY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not scanning anything yet ähnelt.
        /// </summary>
        internal static string SearchNotScanningYet {
            get {
                return ResourceManager.GetString("SearchNotScanningYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}% done ähnelt.
        /// </summary>
        internal static string SearchProgress {
            get {
                return ResourceManager.GetString("SearchProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Files are being scanned ... ähnelt.
        /// </summary>
        internal static string SearchScanningFiles {
            get {
                return ResourceManager.GetString("SearchScanningFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scanning {0} ähnelt.
        /// </summary>
        internal static string SearchScanningFolder {
            get {
                return ResourceManager.GetString("SearchScanningFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skipping {0} - {1} ähnelt.
        /// </summary>
        internal static string SearchSkippingFileOrDirectory {
            get {
                return ResourceManager.GetString("SearchSkippingFileOrDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status: Aborted ähnelt.
        /// </summary>
        internal static string SearchStatusAborted {
            get {
                return ResourceManager.GetString("SearchStatusAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status: Active ähnelt.
        /// </summary>
        internal static string SearchStatusActive {
            get {
                return ResourceManager.GetString("SearchStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status: Completed ähnelt.
        /// </summary>
        internal static string SearchStatusCompleted {
            get {
                return ResourceManager.GetString("SearchStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status: Paused ähnelt.
        /// </summary>
        internal static string SearchStatusPaused {
            get {
                return ResourceManager.GetString("SearchStatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} files scanned ähnelt.
        /// </summary>
        internal static string SearchXFilesScanned {
            get {
                return ResourceManager.GetString("SearchXFilesScanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Shadows found ähnelt.
        /// </summary>
        internal static string SearchXShadowsFound {
            get {
                return ResourceManager.GetString("SearchXShadowsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        internal static string WarningManyFoldersOpeningCaption {
            get {
                return ResourceManager.GetString("WarningManyFoldersOpeningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This action will open a lot of folders and might slow down the computer. Are you sure you wish to continue? ähnelt.
        /// </summary>
        internal static string WarningManyFoldersOpeningText {
            get {
                return ResourceManager.GetString("WarningManyFoldersOpeningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have already added several directories that are subdirectories of &quot;{0}&quot;. If you add this directory, the old ones will be removed from the list, but still be included in the search.
        ///
        ///Do you want to add the new directory? ähnelt.
        /// </summary>
        internal static string WarningMultipleSubfoldersAlreadyAddedText {
            get {
                return ResourceManager.GetString("WarningMultipleSubfoldersAlreadyAddedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have already added the directory &quot;{0}&quot;, which is a subdirectory of &quot;{1}&quot;. If you add the new directory, the old one will be removed from the list, but still be included in the search.
        ///
        ///Do you want to add the new directory? ähnelt.
        /// </summary>
        internal static string WarningSingleSubfolderAlreadyAddedText {
            get {
                return ResourceManager.GetString("WarningSingleSubfolderAlreadyAddedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Already partially added ähnelt.
        /// </summary>
        internal static string WarningSubfolderAlreadyAddedCaption {
            get {
                return ResourceManager.GetString("WarningSubfolderAlreadyAddedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You will be notified as soon as the search has completed. ähnelt.
        /// </summary>
        internal static string WorkingInBackgroundBalloonText {
            get {
                return ResourceManager.GetString("WorkingInBackgroundBalloonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shadows is working in the background ähnelt.
        /// </summary>
        internal static string WorkingInBackgroundBalloonTitle {
            get {
                return ResourceManager.GetString("WorkingInBackgroundBalloonTitle", resourceCulture);
            }
        }
    }
}
